### PR TITLE
split up CUDA-suffixed dependencies in dependencies.yaml

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

Contributes to https://github.com/rapidsai/build-planning/issues/31

In short, RAPIDS DLFW builds want to produce wheels with unsuffixed dependencies, e.g. `cudf` depending on `rmm`, not `rmm-cu12`.

This PR is part of a series across all of RAPIDS to try to support that type of build by setting up CUDA-suffixed and CUDA-unsuffixed dependency lists in `dependencies.yaml`.

For more details, see:
* https://github.com/rapidsai/build-planning/issues/31#issuecomment-2245815818
* https://github.com/rapidsai/cudf/pull/16183

### Why target 24.08?

This is targeting 24.08 because:

1. it should be very low-risk
2. getting these changes into 24.08 prevents the need to carry around patches for every library in DLFW builds using RAPIDS 24.08

### CODE REVIEW

**Comment by jameslamb** [comment]
I've updated this based on the suggestions from https://github.com/rapidsai/cudf/pull/16183.

Ran the following to check `update-version.sh`.

```shell
git fetch upstream --tags
ci/release/update-version.sh '24.10.00'

git grep -E '24\.8|24\.08'
```

Did not find any required changes for that script.

**Comment by jameslamb** [comment]
It looks like the `pip` devcontainer build here is now failing like this:

```text
  /home/coder/cuvs/cpp/src/neighbors/./detail/knn_brute_force.cuh(597): error: no instance of overloaded function "raft::detail::popc" matches the argument list
              argument types are: (const raft::resources, std::experimental::mdspan<const uint32_t, std::experimental::extents<int64_t, 18446744073709551615UL>, raft::layout_c_contiguous, raft::host_device_accessor<std::experimental::default_accessor<const uint32_t>, raft::memory_type::device>>, long, std::experimental::mdspan<int64_t, std::experimental::extents<uint32_t, 1UL>, raft::layout_c_contiguous, raft::host_device_accessor<std::experimental::default_accessor<int64_t>, raft::memory_type::device>>)
      raft::detail::popc(res, filter_view, n_queries * n_dataset, nnz_view);
```

([build link](https://github.com/rapidsai/cuvs/actions/runs/10081825909/job/27874733590?pr=247#step:7:2095))

I see the same error on other recent PRs, like #246 ([build link](https://github.com/rapidsai/cuvs/actions/runs/10080309306/job/27869738758?pr=246)), so strongly suspect it's not related to these changes and that this PR would be safe to admin-merge.

**Comment by jameslamb** [comment]
Cancelling CI here (and will on other commits in the next 24 hours) to save some CI capacity for other projects that are about to enter code freeze.

**Review by bdice — APPROVED** [review]

**Comment by jameslamb** [comment]
This will be blocked until #249 is merged.

Seeing builds fail like this:

```text
  In file included from /__w/cuvs/cuvs/cpp/src/neighbors/brute_force.cu:17:
  /__w/cuvs/cuvs/cpp/src/neighbors/./detail/knn_brute_force.cuh:31:10: fatal error: raft/core/detail/popc.cuh: No such file or directory
     31 | #include <raft/core/detail/popc.cuh>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

([build link](https://github.com/rapidsai/cuvs/actions/runs/10081825909/job/27924045059?pr=247))

**Pull request merged**
