### PR TITLE
Build and test with CUDA 12.5.1

### PR DESCRIPTION
**Pull request by KyleFromNVIDIA**
This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.

Contributes to https://github.com/rapidsai/build-planning/issues/73

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Just one small change, looks like the conda env file mentioned here needs to be updated:

https://github.com/rapidsai/cuvs/blob/37fe9f47c58268129296a58503b1d38aad51822d/docs/source/build.rst#L105

And I think we'll want to update these `cuda-version` references in docs as well:

https://github.com/rapidsai/cuvs/blob/37fe9f47c58268129296a58503b1d38aad51822d/docs/source/build.rst#L46

https://github.com/rapidsai/cuvs/blob/37fe9f47c58268129296a58503b1d38aad51822d/docs/source/build.rst#L53

https://github.com/rapidsai/cuvs/blob/37fe9f47c58268129296a58503b1d38aad51822d/docs/source/build.rst#L60

context: https://github.com/rapidsai/cudf/pull/16259#issuecomment-2231332666

Marking this "approve" so you don't have to wait for another review from me.

**Comment by KyleFromNVIDIA** [comment]
I've updated https://github.com/rapidsai/rapids-reviser/pull/42 to also update `.rst` files.

**Review by jameslamb — APPROVED** [review]
looks good, thank you.

**Review by jakirkham — APPROVED** [review]

**Review by divyegala — APPROVED** [review]

**Pull request merged**
