### PR TITLE
CAGRA: reduce argument count in select_and_run() kernel wrappers

### PR DESCRIPTION
**Pull request by achirkin**
A small change that reduces the number of arguments in one of the wrapper layers in the detail namespace of CAGRA. The goal is twofold:
  1) Simplify the overly long signature of `selet_and_run` (which has many instances) 
  2) Give access to all search parameters for future upgrades of the search kernel

This is to simplify the integration (and review) of the persistent kernel (https://github.com/rapidsai/cuvs/pull/215).
No performance or functional changes expected.

### CODE REVIEW

**Review by tfeher — COMMENTED** [review]
Thanks Artem for the PR! The changes so far look good, but don't we need to change `search_*_cta_kernel-ext.cuh` files too?

**Comment by achirkin** [comment]
Thanks for noticing this, Tamas! I've updated the `*-ext.cuh` files and filed a bug for these files not being used https://github.com/rapidsai/cuvs/issues/242

**Review by tfeher — APPROVED** [review]
Thanks Artem for updating the PR and filing the issue. LGTM.

**Pull request merged**
