### PR TITLE
Add more info to ANN_BENCH context

### PR DESCRIPTION
**Pull request by achirkin**
Add extra information to benchmark context for better reproducibility and performance analysis:

  1. Full command line used to call the executable (so you can copy-paste and run again).
  2. More CUDA device information: whether HMM, AST, or host atomics are available (how GPU can efficiently communicate with CPU).
  3. Host information: min/max frequences, used virtual processors and cores, available physical memory and swap (does the benchmark segfault due to not enough host memory? is SMT enabled? etc).

Addresses parts of https://github.com/rapidsai/cuvs/issues/160

### CODE REVIEW

**Review by tfeher — APPROVED** [review]
Thanks Artem, LGTM, it is useful to extend the context information. I do not see any issues with adding the hostname.

**Comment by tfeher** [comment]
For env vars, I am not sure what would be relevant.
For OpenMP context, you could add [omp_get_max_threads()](https://www.openmp.org/spec-html/5.0/openmpsu112.html)

**Comment by achirkin** [comment]
We could get the openmp-related env vars to see if the limit to the number of threads is set explicitly.
I wouldn't like to add `omp_get_max_threads()` and other OpenMP functions to avoid introducing openmp dependency in the benchmark (for the algorithms that do not use OpenMP and for the ANN_BENCH executable in the single-exe mode). I'm also not sure if cuVS team decides to move away from using OpenMP in favor of standard C++ threads in future.

**Pull request merged**
