### PR TITLE
[WIP] Add pinned memory resource to C API

### PR DESCRIPTION
**Pull request by ajit283**
Let me know if this is out of scope for cuVS!

### CODE REVIEW

**Comment by cjnolet** [comment]
@ajit283 it would be a lot easier to review this PR (and faster to merge it) if you were to isolate the pinned memory resource from the go api changes.

**Comment by ajit283** [comment]
@cjnolet oh sorry, I didn't mean to include those at all

**Review by cjnolet — APPROVED** [review]

**Review by benfred — APPROVED** [review]
Lgtm!

**Pull request merged**
