### PR TITLE
Add `kIsSingleSource` to `PairwiseDistanceEpilogueElementwise`

### PR DESCRIPTION
**Pull request by KyleFromNVIDIA**
With raft having recently migrated to cutlass 3.5.1, this field is now required.

Also remove `raft_cutlass` from symbol exclusions.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Comment by KyleFromNVIDIA** [comment]
cc @jackkosaian

**Comment by KyleFromNVIDIA** [comment]
We need to remove `raft_cutlass` from symbol exclusions. I have a commit that does this locally and will push it once this round of CI finishes.

**Review by vyasr — APPROVED** [review]

**Review by bdice — APPROVED** [review]
Thanks @KyleFromNVIDIA! Approving additional changes.

**Review by lowener — APPROVED** [review]

**Pull request merged**
