### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

Contributes to https://github.com/rapidsai/build-planning/issues/40

This PR adds support for Python 3.12.

## Notes for Reviewers

This is part of ongoing work to add Python 3.12 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.12, from https://github.com/rapidsai/shared-workflows/pull/213.

A follow-up PR will revert back to pointing at the `branch-24.10` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.12 support.

### This will fail until all dependencies have been updates to Python 3.12

CI here is expected to fail until all of this project's upstream dependencies support Python 3.12.

This can be merged whenever all CI jobs are passing.

### CODE REVIEW

**Comment by jameslamb** [comment]
Restarted CI here now that there are Python 3.12 packages for `raft`: https://github.com/rapidsai/raft/pull/2428

Will put this up for review once I see enough of CI passing.

**Review by bdice — APPROVED** [review]

**Review by bdice — COMMENTED** [review]
We may also want to update https://github.com/rapidsai/cuvs/blob/bdea78ebcc9e540ccd62dbe24f46f954b853d816/python/cuvs_bench/pyproject.toml#L28-L30 to drop 3.9 and add 3.12?

(edit: it was just added 13 hours ago in #275 -- you didn't miss this)

**Comment by bdice** [comment]
I am going to merge this PR and then do a follow-up for updating the new `cuvs_bench` changes. CI has already passed here and we don't need to delay merging any further (these changes should be tested with other PRs going forward).

**Comment by jameslamb** [comment]
Ok thanks very much! Yep I hadn't noticed that new `cuvs_bench` stuff package, thanks for catching it.

**Comment by bdice** [comment]
Follow-up here: https://github.com/rapidsai/cuvs/pull/318

**Pull request merged**
